server:
  port: 9004

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:

        - id: customer-microservice
          uri: lb://customer-microservice
          predicates:
            - Path=/api/customers/**

        - id: flight-microservice
          uri: lb://flight-microservice
          predicates:
            - Path=/api/flights/**

        - id: reservation-microservice
          uri: lb://reservation-microservice
          predicates:
            - Path=/api/reservations/**

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"

#eureka:xw
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka